### ISSUE TITLE
Create Mock

### ISSUE THREAD

**Issue by kaitlynhova** [matthova/Bart-Native#1]
## Issue
We need to make this app pretty.

## Solution
- [x] Create a mock that does this that incorporates different train colors

**Comment by kaitlynhova** [comment]
![hova-labs-bart-party](https://user-images.githubusercontent.com/5474124/39032003-69904482-4420-11e8-9f0e-3de3c9b3c313.jpg)

**Comment by matthova** [comment]
Nice! Lets do it
